import type { Metadata } from "next";

import "./globals.css";
import { ConvexClientProvider } from "./ConvexClientProvider";

import { ClerkProviderWrapper } from "@/components/ClerkProviderWrapper";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body >
        <ClerkProviderWrapper>
          <ConvexClientProvider>
            <div className="h-screen bg-beige overflow-y-hidden">
              {children}
            </div>
          </ConvexClientProvider>
       </ClerkProviderWrapper>
        </body>
      </html>
  );
}